
package com.univesp.jaba;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author helton
 */
public class CadInsumo extends javax.swing.JFrame {
    ArrayList<Insumo> listaInsumo;
    
    public void LoadTableIns(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Nome", "Unidade","Quantidade","Custo"},0);
        
        for(int i=0;i<listaInsumo.size();i++){
            Object linha [] = new Object[] {listaInsumo.get(i).getNome(),
                                            listaInsumo.get(i).getUnidade(),
                                            listaInsumo.get(i).getQuantidade(),
                                            listaInsumo.get(i).getCusto()};
            
            modelo.addRow(linha);
        }        
        
        tbl_ins.setModel(modelo);
        tbl_ins.getColumnModel().getColumn(0).setPreferredWidth(60);
        tbl_ins.getColumnModel().getColumn(0).setPreferredWidth(15);
        tbl_ins.getColumnModel().getColumn(0).setPreferredWidth(15);
        tbl_ins.getColumnModel().getColumn(0).setPreferredWidth(15);

    }   
    
    public CadInsumo() {
        initComponents();
        setLocationRelativeTo(null);
        listaInsumo = new ArrayList();
        ManipulaInterface("navegar");
    }

    public void ManipulaInterface(String modo){
        switch(modo){
            case "navegar":
                btn_ins_novo.setEnabled(true);
                btn_ins_cancelar.setEnabled(false);
                btn_ins_editar.setEnabled(false);
                btn_ins_excluir.setEnabled(false);
                btn_ins_salvar.setEnabled(false);
                c_ins_custo.setEnabled(false);
                c_ins_nome.setEnabled(false);
                c_ins_quant.setEnabled(false);
                c_ins_unid.setEnabled(false);
                break;
            
            case "novo":
                btn_ins_novo.setEnabled(false);
                btn_ins_cancelar.setEnabled(true);
                btn_ins_editar.setEnabled(false);
                btn_ins_excluir.setEnabled(false);
                btn_ins_salvar.setEnabled(true);
                c_ins_custo.setEnabled(true);
                c_ins_nome.setEnabled(true);
                c_ins_quant.setEnabled(true);
                c_ins_unid.setEnabled(true);                
                break;
                
            case "editar":
                btn_ins_novo.setEnabled(true);
                btn_ins_cancelar.setEnabled(true);
                btn_ins_editar.setEnabled(false);
                btn_ins_excluir.setEnabled(false);
                btn_ins_salvar.setEnabled(false);
                c_ins_custo.setEnabled(true);
                c_ins_nome.setEnabled(true);
                c_ins_quant.setEnabled(true);
                c_ins_unid.setEnabled(true);                
                break;
                
            case "excluir":
                btn_ins_novo.setEnabled(true);
                btn_ins_cancelar.setEnabled(false);
                btn_ins_editar.setEnabled(false);
                btn_ins_excluir.setEnabled(true);
                btn_ins_salvar.setEnabled(false);
                c_ins_custo.setEnabled(false);
                c_ins_nome.setEnabled(false);
                c_ins_quant.setEnabled(false);
                c_ins_unid.setEnabled(false);
                break;
                
            case "selecao":
                btn_ins_novo.setEnabled(false);
                btn_ins_cancelar.setEnabled(false);
                btn_ins_editar.setEnabled(true);
                btn_ins_excluir.setEnabled(true);
                btn_ins_salvar.setEnabled(false);
                c_ins_custo.setEnabled(false);
                c_ins_nome.setEnabled(false);
                c_ins_quant.setEnabled(false);
                c_ins_unid.setEnabled(false);
                break;
            default:System.out.println("Modo inválido");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_ins = new javax.swing.JTable();
        btn_ins_novo = new javax.swing.JButton();
        btn_ins_editar = new javax.swing.JButton();
        btn_ins_excluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        c_ins_nome = new javax.swing.JTextField();
        c_ins_unid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c_ins_quant = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        c_ins_custo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_ins_salvar = new javax.swing.JButton();
        btn_ins_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(2);
        jTextArea1.setText("Produtos comprados prontos e que são usados na preparação dos seus lanches");
        jTextArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(jTextArea1);

        tbl_ins.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nome", "Unid", "Qtd", "Custo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_ins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_insMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_ins);
        if (tbl_ins.getColumnModel().getColumnCount() > 0) {
            tbl_ins.getColumnModel().getColumn(0).setResizable(false);
            tbl_ins.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbl_ins.getColumnModel().getColumn(1).setResizable(false);
            tbl_ins.getColumnModel().getColumn(1).setPreferredWidth(15);
            tbl_ins.getColumnModel().getColumn(2).setResizable(false);
            tbl_ins.getColumnModel().getColumn(2).setPreferredWidth(15);
            tbl_ins.getColumnModel().getColumn(3).setResizable(false);
            tbl_ins.getColumnModel().getColumn(3).setPreferredWidth(15);
        }

        btn_ins_novo.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        btn_ins_novo.setText("novo");
        btn_ins_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ins_novoActionPerformed(evt);
            }
        });

        btn_ins_editar.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        btn_ins_editar.setText("editar");
        btn_ins_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ins_editarActionPerformed(evt);
            }
        });

        btn_ins_excluir.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        btn_ins_excluir.setText("excluir");

        jLabel1.setFont(new java.awt.Font("Chilanka", 0, 24)); // NOI18N
        jLabel1.setText("matérias primas");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar matéria-prima"));

        jLabel2.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jLabel2.setText("nome");

        c_ins_nome.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N

        c_ins_unid.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jLabel3.setText("unidade");

        c_ins_quant.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jLabel4.setText("quantidade");

        c_ins_custo.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        jLabel5.setText("custo");

        btn_ins_salvar.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        btn_ins_salvar.setText("salvar");
        btn_ins_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ins_salvarActionPerformed(evt);
            }
        });

        btn_ins_cancelar.setFont(new java.awt.Font("Chilanka", 0, 14)); // NOI18N
        btn_ins_cancelar.setText("cancelar");
        btn_ins_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ins_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(c_ins_nome))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(c_ins_unid))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(c_ins_quant, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_ins_custo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_ins_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ins_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(c_ins_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(c_ins_unid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(c_ins_quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_ins_custo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ins_salvar)
                    .addComponent(btn_ins_cancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_ins_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_ins_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ins_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ins_novo)
                    .addComponent(btn_ins_editar)
                    .addComponent(btn_ins_excluir))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ins_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ins_novoActionPerformed
        c_ins_nome.setText("");
        c_ins_unid.setText("");
        c_ins_quant.setText("");    
        c_ins_custo.setText("");   
        ManipulaInterface("novo");
    }//GEN-LAST:event_btn_ins_novoActionPerformed

    private void btn_ins_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ins_cancelarActionPerformed
        c_ins_nome.setText("");
        c_ins_unid.setText("");
        c_ins_quant.setText("");    
        c_ins_custo.setText("");   
        ManipulaInterface("navegar");
    }//GEN-LAST:event_btn_ins_cancelarActionPerformed

    private void btn_ins_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ins_salvarActionPerformed
        int quant = Integer.parseInt(c_ins_quant.getText());
        float cust = Float.parseFloat(c_ins_custo.getText());
        
        Insumo I = new Insumo(c_ins_nome.getText(), c_ins_unid.getText(), quant, cust);
        
        listaInsumo.add(I);
        
        LoadTableIns();
        ManipulaInterface("navegar");
        c_ins_nome.setText("");
        c_ins_unid.setText("");
        c_ins_quant.setText("");    
        c_ins_custo.setText("");
    }//GEN-LAST:event_btn_ins_salvarActionPerformed

    private void tbl_insMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_insMouseClicked
        int index = tbl_ins.getSelectedRow();
        if(index >= 0 && index <=listaInsumo.size()){
        
        Insumo I = listaInsumo.get(index);
            
        c_ins_nome.setText(I.getNome());
        c_ins_unid.setText(I.getUnidade());
        c_ins_quant.setText(String.valueOf(I.getQuantidade()));
        c_ins_custo.setText(String.valueOf(I.getCusto()));
        ManipulaInterface("selecao");
        }
    }//GEN-LAST:event_tbl_insMouseClicked

    private void btn_ins_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ins_editarActionPerformed
        ManipulaInterface("editar");
    }//GEN-LAST:event_btn_ins_editarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadInsumo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ins_cancelar;
    private javax.swing.JButton btn_ins_editar;
    private javax.swing.JButton btn_ins_excluir;
    private javax.swing.JButton btn_ins_novo;
    private javax.swing.JButton btn_ins_salvar;
    private javax.swing.JTextField c_ins_custo;
    private javax.swing.JTextField c_ins_nome;
    private javax.swing.JTextField c_ins_quant;
    private javax.swing.JTextField c_ins_unid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tbl_ins;
    // End of variables declaration//GEN-END:variables
}
